apollographql/embeddable-explorer

package-lock.json, package.json
If this looks good, I'll publish the package using an npm tag other than `latest` (let's call it `next`), which should allow you to run `npm i @apollo/explorer@0.1.0` and test the package locally (if you like). Once you feel good about that, I'll retag version 0.1.0 as `latest` so it can be installed using just `npm i @apollo/explorer`.
I did try to address some `npm audit` security warnings, but those all have to do with `devDependencies`, and this package has no `dependencies`, so consumers of this package should not have to worry about those dev-only security advisories.
=> Prep for first npm publish as `@apollo/explorer`

README.md
Now, folks can install the embeddable explorer through the npm package. We should let them know! We should also update the embedded explorer experience in studio.
=> Update README.md for npm package

package.json
[Ben renamed the name of the embeddable explorer repo](https://github.com/apollographql/embeddable-explorer/pull/13) in package.json to @apollo/explorer before he published to npm. That changed the generated files to prefix with `explorer...` instead of `embeddable-explorer...` [seen here](https://console.cloud.google.com/storage/browser/embeddable-explorer/_latest?project=mdg-services&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false). This means folks are embedding and being told to embed
```
<script src="https://embeddable-explorer.cdn.apollographql.com/_latest/embeddable-explorer.umd.production.min.js"></script> 
<script>
new window.EmbeddedExplorer({
```
which exists but is out of date.
This PR explicitly passes a name, …
=> 🐛 keep built files name consistent

renovate.json5
Renovate PR https://github.com/apollographql/embeddable-explorer/pull/35 is failing because of peer dependency issues - `size-limit` updates need to be grouped in order for this to work. This should result in a renovate PR which updates both `size-limit` and `@size-limit/file` at the same time.
=> Group `size-limit` dependency updates

.changeset/late-turtles-rush.md, src/react/index.tsx
I noticed 2 embeds for react showing up in the example code sandbox: https://codesandbox.io/s/npm-embeddable-explorer-zotwkv?file=/src/index.js
Should have caught this with the lint warnings!
=> Make `currentEmbed` a ref

.changeset/green-geese-play.md, src/EmbeddedExplorer.ts, src/react/index.tsx
[JIRA](https://apollographql.atlassian.net/browse/NEBULA-1153)
Expose schema: Now that we are passing schema to the react component for the AS Landing Page v2: embed, we want to just allow this I imagine. No reason to hide it from folks anymore?
Remove sendRequestsFrom: this was never exposed, and I don't see a reason to keep it around. Now it becomes a security issue as well (see jira)
=> Expose schema as an option to pass & remove sendRequestsFrom

.changeset/pink-geckos-behave.md, package-lock.json, package.json, src/EmbeddedExplorer.ts, src/constants.ts, src/examples/react-example/exampleSchema.ts, src/examples/react-example/index.tsx, src/examples/react-example/package.json, src/react/index.tsx, src/setupEmbedRelay.ts
~Previously, we were tearing down the existing embed and setting up a new instance of EmbeddedExplorer when params changed.~
~Now, we have a corresponding studio-ui PR that, when combined with this one, will accept pm's from the parent page when params change, and update them dynamically in the embed. No local state is lost!~
This PR is a necessary pre req to setting up the embed in Apollo Server, because the schema may dynamically change & we need to update it. The schema & param pm messages are different, because [we already listen for `SCHEMA_RESPONSE` in `useSchema` in studio-ui](https://github.com/mdg-private/studio-ui/blob/main/src/app/graph/hooks/useSchema.tsx#L134), and it is not a query param. 
[JIRA](https://apollographql.atlassian.net/browse/NEBULA-1161)
=> NEBULA-1161: pm schema to embed when schema changes

.changeset/purple-forks-hang.md, src/embeddedExplorer/EmbeddedExplorer.ts
This grey border shows up on all embeds, I think we want to remove it by default for all embeds.
=> remove grey border on default iframes

src/embeddedSandbox/EmbeddedSandbox.ts, src/embeddedSandbox/examples/localDevelopmentExample.html, src/helpers/constants.ts
Adding the 'endpoint' query param means that AS3 can start the endpoint at the current server url.
=> Support initial endpoint in Embedded Sandbox

.changeset/perfect-coats-cry.md, src/embeddedExplorer/EmbeddedExplorer.ts, src/embeddedExplorer/setupEmbedRelay.ts, src/helpers/postMessageRelayHelpers.ts
We want producers of the embed to be able to configure settings to auto-invite users to the embedded graph's org when they authenticate.
- Checkout to `william/auto-invite-org` on embeddable-explorer
- Checkout to `william/explorer-everywhere/auto-invite-org` on studio-ui
- Edit `embeddedExplorer/examples/localDevelopmentExample.html`, change graphRef to a private graph (that you aren't authorized on yet) and add `inviteToken` and `accountId`
```
new window.EmbeddedExplorer({
target: '#embeddableExplorer',
graphRef: 'graph@current',
endpointUrl: 'https://acephei-gateway.herokuapp.com',
inviteToken: ASK WILLIAM,
accountId: 'will-test-org',
```
- `npm run build-explorer:umd` on embeddable-explorer
- `npm run start:embedded` on studio-ui
- Open localDevelopmentExample in the …
=> NEBULA-1163: Add optional config for inviteToken and accountId

.changeset/wet-hornets-hope.md, package.json
I moved these files around in a different PR, but forgot to repoint the cjs / esm build command!
=> point to correct index file for cjs/esm build

.changeset/three-apples-behave.md, src/embeddedExplorer/setupEmbedRelay.ts, src/embeddedSandbox/setupSandboxEmbedRelay.ts, src/helpers/postMessageRelayHelpers.ts
We forgot to add this to sandbox when we added it to explorer!
I moved it into a shared function - do you like that, or is it okay to be copied twice?
=> listen for auth stuff in sandbox too

README.md, src/embeddedExplorer/examples/react-example/package.json, src/embeddedExplorer/react/index.tsx
We were seeing the error `useDeepCompareEffect should not be used with dependencies that are all primitive values.` in the React embedded Explorer. This is because the objects in the `useDeepCompareEffect` are optional - so if they are all undefined, it's all primitives in there.
This PR defaults to an empty object for the object types, so there are always objects in the deep compare effect
=> 🐛 fix but where useDeepCompareEffect expects objects

.changeset/selfish-trains-approve.md, README.md, src/embeddedExplorer/EmbeddedExplorer.ts, src/embeddedExplorer/examples/react-example/package.json, src/embeddedExplorer/react/index.tsx, src/embeddedSandbox/EmbeddedSandbox.ts, src/helpers/defaultHandleRequest.ts
Pass through `includeCookies` to default fetch handler for both embedded sandbox & explorer
=> add config option: `includeCookies`

.changeset/tiny-camels-behave.md, src/helpers/constants.ts, src/helpers/postMessageRelayHelpers.ts
[JIRA](https://apollographql.atlassian.net/browse/NEBULA-1288)
We want to send a PM to the parent when a user clicks 'log out' to clear the parent local storage and then send a PM back that we listen for in the useEmbedUserToken , and clear the embedUserToken & local storage.
=> NEBULA-1288: Add logout messages to parent

.changeset/brave-snakes-rhyme.md, src/embeddedExplorer/EmbeddedExplorer.ts, src/embeddedSandbox/EmbeddedSandbox.ts
Previously I had this logic
```
Object.assign(element?.style, { height: element?.style.height || '100%' });
Object.assign(element?.style, { width: element?.style.width || '100%' });
```
to default to full screen iframe for the embedded Explorer. This only checked if `style` attributes were set by the user. Folks may set `className`, and this was overriding their classes, so lets not do anything if they have already set className either.
=> respect classes that folks applied to their embed elements

.changeset/grumpy-bees-rest.md, src/embeddedExplorer/setupEmbedRelay.ts, src/embeddedSandbox/setupSandboxEmbedRelay.ts
This is showing up on code sandbox examples, bad look!
This PR: 
- checks if data is an object & if data.name exists before doing anything else :)
=> get rid of 'cannot use in operator' type error shown in development

.changeset/purple-keys-sniff.md, src/embeddedExplorer/EmbeddedExplorer.ts
apollo dev tools v 4.0.0 doesn't send this query param, so we need it to default to false on the studio end so the folks on v 4.0.0 don't see the header.
=> 🐛 🩹 always send `shouldShowGlobalHeader` as true from this repo

.changeset/dirty-donuts-switch.md, src/embeddedExplorer/EmbeddedExplorer.ts
once folks bundles are updated to not REQUIRE the `sendRequestsFrom` param, we can release this.
=> 🚨 Remove `sendRequestsFrom` 🚨 DON'T MERGE UNTIL  https://github.com/mdg-private/studio-ui/pull/6154 IS OUT 🚨 

package.json
I am confused because according to[ this comment](https://github.com/codesandbox/codesandbox-ci-ui/issues/40#issuecomment-1141960749) and what we have seen in playing around debugging npm publishes before, the built cjs / esm files are built prefixed with `explorer` when you pull them down from npm, but when built locally they are prefixed with `embeddable-explorer`?
Test by clicking on the code sandbox deploy preview below and see that it all works!
=> code sandbox deploy preview 🐛 fix

src/helpers/postMessageRelayHelpers.ts
These were a copy-paste artifact, but there are no operation ids for the schema pms
=> 🧹 Remove incorrect comments

.codesandbox/ci.json, README.md, buildHelpers/createRollupConfig.js, buildHelpers/prepareDist.js, package-lock.json, package.json, src/embeddedExplorer/examples/react-example/index.tsx, src/index.ts, src/react/index.cjs, src/react/index.ts
This PR changes the import style of our npm package from 
```
import { ApolloExplorer, ApolloExplorerReact } from '@apollo/explorer';
const { ApolloExplorer, ApolloExplorerReact } = require('@apollo/explorer');
```
to 
```
import { ApolloExplorer } from '@apollo/explorer';
import { ApolloExplorer } from '@apollo/explorer/react';
const { ApolloExplorer } = require('@apollo/explorer');
const { ApolloExplorer } = require('@apollo/explorer/react');
```
**How?**
I created a /react folder in /src with a single index.ts file that exports the React component, and specified this as an entry point for rollup to build. When the build is built, all of this is in the dist folder. When we publish to npm, we publish from the dist folder so folks can import from `@apollo/explorer/react` instead of …
=> Split React export into its own file

.changeset/fast-bulldogs-bathe.md, src/embeddedExplorer/EmbeddedExplorer.ts, src/embeddedSandbox/EmbeddedSandbox.ts
[JIRA](https://apollographql.atlassian.net/browse/NEBULA-1385)
- Added initialState with document, headers and variables for embeddable sandbox
- Checkout to `william/sandbox-initial-state` on `embeddable-explorer` repo
- Checkout to `william/explorer-everywhere/sandbox-initial-state` on `studio-ui` repo
- Change `constants.ts` to `EMBEDDABLE_SANDBOX_URL =
'https://embed.apollo.local:3000/sandbox/explorer';`
- Add an initial state to the embed configuration, for example:
```
initialState: {
document: `query Test {
me {
id
}
}`,
variables: {
test: 'abcxyz',
},
headers: {
'key': 'value'
},
```
- `npm run build-sandbox:umd` on embeddable-explorer
- `npm run start:embedded` on studio-ui
- Open localDevelopmentExample for embedded Sandbox on Go Live
- Close all tabs to see initial state …
=> NEBULA-1385: Add initialState config for sandbox

packages/explorer/src/EmbeddedExplorer.ts, packages/explorer/src/examples/localDevelopmentExample.html, packages/explorer/src/examples/react-example/index.tsx, packages/explorer/src/helpers/postMessageRelayHelpers.ts, packages/explorer/src/react/ApolloExplorer.tsx, packages/explorer/src/setupEmbedRelay.ts, packages/sandbox/src/setupSandboxEmbedRelay.ts
studio PR: 
https://github.com/mdg-private/studio-ui/pull/6424
This would be a major npm update since the types would throw. I think we'd also want a major npm update for the new sandbox package & /react imports - se we'd bundle these
=> make endpointUrl only required when schema is passed DON'T RELEASE UNTIL STUDIO PR IS OUT FOR A WHILE

.changeset/silver-fans-try.md, packages/explorer/src/examples/react-example/package.json, packages/sandbox/src/examples/react-example/package.json
`npm run start` was not working for react-example
The files were moved, so the relative path needed to be fixed
=> Fix relative path for react-example alias

packages/explorer/src/EmbeddedExplorer.ts, packages/explorer/src/helpers/constants.ts, packages/explorer/src/helpers/postMessageRelayHelpers.ts, packages/explorer/src/setupEmbedRelay.ts, packages/sandbox/src/EmbeddedSandbox.ts, packages/sandbox/src/helpers/constants.ts, packages/sandbox/src/helpers/postMessageRelayHelpers.ts, packages/sandbox/src/setupSandboxEmbedRelay.ts
We want to add smoke tests for the embeddable Explorer / Sandbox. To do this in cypress / circle ci, we need to spin up a local embed build of studio-ui via `npm run start:embedded`, and then we need to spin up a little html embed site that uses the embeddable-explorer code on the cdn to embed the site, and we will need to point to the local https://embed.apollo.local:3000 running site.
We can use this option to point to the local running site instead of studio developed.
=> Add test-only local url option

.github/workflows/release-pr.yaml
We might want to add commits to branch version-0 which is the source of truth for @apollo/explorer < 1.0.0. 
This will check that branch for changes as well!
=> add version-0 to release branch options

.changeset/hungry-tips-speak.md, packages/explorer/src/EmbeddedExplorer.ts, packages/sandbox/src/EmbeddedSandbox.ts
We don't want to run telemetry on dev tools: https://apollograph.slack.com/archives/C01GC140SUV/p1655387856372719
So we are going to opt out by default on the embedded sites, but lets pass an opt in from here! So all newer versions get telemetry
=> Add opt-in query param for Studio telemetry & cookie notice

.changeset/lemon-glasses-bow.md, package-lock.json, package.json, packages/explorer/src/helpers/constants.ts, packages/explorer/src/helpers/postMessageRelayHelpers.ts, packages/explorer/src/helpers/readMultipartWebStream.ts, packages/sandbox/src/helpers/constants.ts, packages/sandbox/src/helpers/postMessageRelayHelpers.ts, packages/sandbox/src/helpers/readMultipartWebStream.ts
[JIRA](https://apollographql.atlassian.net/browse/NEBULA-1271)
[Related studio-ui PR](https://github.com/mdg-private/studio-ui/pull/6647)
- Added support for `@defer` and `@stream` in embedded Explorer and embedded Sandbox
- Added `EXPLORER_PARTIAL_RESPONSE` listener to send PMs to studio when observing a multipart response
- Checkout to `william/embedded-defer` in the `embeddable-explorer` repo
- Checkout to `william/defer/embedded-defer` in `studio-ui`
- Add `__testLocal__: true,` in `localDevelopmentExample.html`
- `npm run start:embedded` on `studio-ui`
- `cd packages/sandbox && npm run build:umd` on `embeddable-explorer`
- `cd packages/explorer && npm run build:umd` on `embeddable-explorer`
```
git clone git@github.com:contra/graphql-helix.git
cd graphql-helix
yarn
npm i cors
npm i …
```
=> NEBULA-1271: Support @defer in embedded Explorer and embedded Sandbox

.changeset/unlucky-books-add.md, packages/sandbox/src/EmbeddedSandbox.ts
In prep for up coming toggle to send a header to router that will make it return the query plan, we want to allow embed to pass the initial value for the request query plan toggle. This way, routers internal sandbox embed can make this default to true.
This corresponds with https://github.com/mdg-private/studio-ui/pull/6986  which is the PR that reads this value
https://apollographql.atlassian.net/browse/NEBULA-1604
=> Allow passing initialRequestQueryPlan

package-lock.json, package.json, packages/explorer/src/helpers/postMessageRelayHelpers.ts, packages/explorer/src/helpers/subscriptionPostMessageRelayHelpers.ts, packages/sandbox/package-lock.json, packages/sandbox/src/helpers/postMessageRelayHelpers.ts, packages/sandbox/src/helpers/subscriptionPostMessageRelayHelpers.ts
this PR 
- updated graphql-js to version 16.X
- changes the types of some of the subscription data to be aligned with typescript. 
subscription-transport-ws wants everything to by typed as `ObjMap`, which is really just an object as far as I can tell:
```
export interface ObjMap<T> {
[key: string]: T;
}
```
vs
```
export type JSONPrimitive = boolean | null | string | number;
export type JSONObject = { [key in string]?: JSONValue };
export type JSONValue = JSONPrimitive | JSONValue[] | JSONObject;
```
Looking for verification that this is an okay thing to do. 
**How to test**
start up embedded Sandbox & input a subscription endpoint (preferably one of each subscription-transport-ws & graphql-ws) and run a subscription & make sure it works
=> Update GraphQL to 16 

.changeset/plenty-shrimps-breathe.md, packages/explorer/src/helpers/postMessageRelayHelpers.ts, packages/explorer/src/setupEmbedRelay.ts, packages/sandbox/src/helpers/postMessageRelayHelpers.ts, packages/sandbox/src/setupSandboxEmbedRelay.ts
We [upgraded to TS4 a week ago](https://github.com/apollographql/embeddable-explorer/pull/171), so now we can use the generic MessageEvent type.
This PR includes one change that have happened in the studio <> embed communication before I commented out MessageEvent generics, which is to send `endpointUrl` instead of `sandboxEndpointUrl`
=> Support Generic MessageEvent type now that we are on TS4 :)

package-lock.json, package.json, packages/explorer/package-lock.json, packages/explorer/package.json, packages/sandbox/package.json
in response to: https://github.com/apollographql/embeddable-explorer/issues/166"
We need this dep for the sandbox & explorer packages
=> add zen-observable-ts to each package file individually, not whole project

.changeset/mighty-sloths-eat.md, packages/explorer/buildHelpers/createRollupConfig.js, packages/sandbox/buildHelpers/createRollupConfig.js
https://github.com/apollographql/embeddable-explorer/issues/160
this particular part of this error ^ is important: 
```
index.development.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
```
we were naming our intermediate cjs exports as .js instead of .cjs, and since our package.json has type: module Next.js was throwing build errors. This rollup config change should solve that. 
I confirmed it outputs .cjs files.
=> 🐛 Fixes Issue#160: name cjs files .cjs so they don't conflict with type:module

packages/sandbox/src/EmbeddedSandbox.ts
corresponding studio-ui PR: https://github.com/mdg-private/studio-ui/pull/7884
This PR adds an `endpointIsEditable` option. Defaults to true, when false, endpoint in the Sandbox header is static,
**🚨 MERGE STUDIO PR FIRST🚨** 
**Note**
This PR is being merged into the version branch, studio PRs can be merged into main with no change in behavior, but embedded-explorer PRs should be release all in one minor version
=> NEBULA-1841: pass through endpoint is editable config to embeddable sandbox

packages/sandbox/src/EmbeddedSandbox.ts, packages/sandbox/src/helpers/postMessageRelayHelpers.ts, packages/sandbox/src/setupSandboxEmbedRelay.ts
[Corresponding Studio PR
](https://github.com/mdg-private/studio-ui/pull/7874)
We had an issue where studio sends of multiple introspection requests, and we need to be able to identify the different ones. We weren't sending operation ids for introspection requests, but we were for all other requests. Adding operationIds to introspection ids.
=> 🐛 🩹 send operation ids for introspection requests 🚨 wait for nebula-2002 before merge🚨 

.changeset/famous-needles-explode.md, packages/sandbox/src/EmbeddedSandbox.ts
corresponding studio-ui PR: https://github.com/mdg-private/studio-ui/pull/7878
This PR adds an initialState option `pollForSchemaUpdates`, when false the autopoll option will be off
**🚨 MERGE STUDIO PR FIRST🚨** 
**Note**
This PR is being merged into the version branch, studio PRs can be merged into main with no change in behavior, but embedded-explorer PRs should be release all in one minor version
=> NEBULA-1859: pass through `pollForSchemaUpdates` to control auto poll

packages/sandbox/src/EmbeddedSandbox.ts
Pass through shared headers from config for Sandbox. For Explorer, folks should set these on their graph
**Do we think that `sharedHeaders` makes sense in `initialState` in the embedded Sandbox api? Should it be not under `initialState`, since the shared headers won't change, but the checked state could.... I am not sure**
@cheapsteak @esilverm ^ thoughts?
=> NEBULA-2069: Allow shared headers from config

packages/explorer/src/EmbeddedExplorer.ts, packages/sandbox/src/EmbeddedSandbox.ts
Users should only pass one or another of these, not both!
=> Type fix: only allow user to pass collectionId / operationId OR document, variables, headers

packages/explorer/README.md
=> fix README's links to examples

packages/explorer/src/helpers/constants.ts, packages/explorer/src/helpers/postMessageRelayHelpers.ts, packages/explorer/src/helpers/readMultipartWebStream.ts, packages/explorer/src/helpers/subscriptionPostMessageRelayHelpers.ts, packages/explorer/src/setupEmbedRelay.ts
Now that we have [autocomplete](https://github.com/mdg-private/studio-ui/pull/8332) for subscriptions, we can support subscriptions in the embedded Explorer as well as the embedded Sandbox
This PR copies the `helpers` folder from /sandbox to /explorer & does a bit of tweaking, like removing the introspection queries that we don't use in explorer, renaming from sandbox to explorer. 
It should match the changes in this [PR](https://github.com/apollographql/embeddable-explorer/pull/224) exactly, with the additions in [this PR](https://github.com/apollographql/embeddable-explorer/pull/231)
=> Support multipart subs in explorer too

.changeset/kind-zoos-press.md, packages/explorer/src/examples/localDevelopmentExample.html, packages/explorer/src/helpers/constants.ts, packages/explorer/src/helpers/postMessageRelayHelpers.ts, packages/explorer/src/helpers/readMultipartWebStream.ts, packages/explorer/src/helpers/subscriptionPostMessageRelayHelpers.ts, packages/explorer/src/setupEmbedRelay.ts, packages/sandbox/src/helpers/postMessageRelayHelpers.ts, packages/sandbox/src/helpers/readMultipartWebStream.ts
https://apollograph.slack.com/archives/C026H578D6K/p1680189926960089
The multipart subscription protocol now doesn't send `done: true`, we rely on the `--graphql--` message boundary to know to terminate. 
This PR updates the termination logic to be passed from `readMultipartWebstream` finding a `--graphql--` message boundary with the -- dash at the end & removes `done: true` from the accepted types for an http subscription.
This PR also makes `payload` nullable, since it will always be present, but when errors come back from the http subscription it will be null.
[Follow these instructions](https://apollograph.slack.com/archives/C026H578D6K/p1678190088438199?thread_ts=1678147601.919469&cid=C026H578D6K)
Open `localDevelopmentExample` in [the embeddable-explorer repo on this …
=> Update multipart subs protocol

packages/sandbox/src/EmbeddedSandbox.ts
https://apollograph.slack.com/archives/C026H578D6K/p1681839839729999
on the embedded Sandbox (used by router & apollo server) we specify that the endpoint url is not editable by default. The router has no config options for the users to pass, so the endpoints are not editable ever. 
This is an issue, because we don't have a way for folks to specify their subscription url at all, its just assumed that it is the ws of the endpoint url.
This PR allows passing through the subscription url explicitly. 
[See studio-ui PR accepting this query param here](https://github.com/mdg-private/studio-ui/pull/8427c)
Run embedded Sandbox locally with `npm run start:embedded -w studio`, build [this embeddable-explorer branch ](https://github.com/apollographql/embeddable-explorer/pull/250), run …
=> pass through subscription endpoint

.changeset/quick-points-drop.md, packages/explorer/README.md, packages/explorer/src/EmbeddedExplorer.ts, packages/sandbox/README.md, packages/sandbox/src/EmbeddedSandbox.ts
The dynamic style additions to the iframe were causing CSP errors for consumers. Lets not dynamically add styling for AS, which enforces a content security policy, we will style in the app there
=> Add opt out option `allowDynamicStyling` for CSP enforcers

.changeset/twelve-hats-burn.md, packages/sandbox/src/EmbeddedSandbox.ts
https://apollograph.slack.com/archives/C021CUR8WCD/p1695311045449899
We need to pass this as a config b/c AS4 defaults to `_latest` if no one passes a version, and even if we pin a version now, older versions will have changes they don't expect. So we will add a config, default it to the current behavior. Add documentation to encourage folks to make this false & update the default behavior in the hosted Sandbox
=> sendOperationHeadersInIntrospection config option, default to true

.circleci/config.yml
Trevor and I discussed publishing buckets under major versions so AS 5 can pin major versions
Published by removing the circle branch filters:
https://console.cloud.google.com/storage/browser/embeddable-sandbox/v2;tab=objects?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&project=mdg-services&prefix=&forceOnObjectsSortingFiltering=false
https://console.cloud.google.com/storage/browser/embeddable-explorer/v3?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&project=mdg-services&prefix=&forceOnObjectsSortingFiltering=false
=> Publish Major versioned CDN folders

.changeset/fuzzy-fans-invite.md, packages/sandbox/src/EmbeddedSandbox.ts
We have introduced a new setting config for the embedded sandbox that will allow us to automatically request connectors debugging information for display in Explorer.
=> Adding support for `initialRequestConnectorsDebugging` to `EmbeddableSandbox`

renovate.json5
Only make PRs for vulnerabilities. This removes some configuration that did grouping. We couldn't figure out how to have both before and limiting to vulnerabilities should reduce noise more then grouping.
=> update renovate config

.circleci/config.yml
cdn-upload-*  tasks were failing with error of "sudo: command not found"
https://app.circleci.com/pipelines/github/apollographql/embeddable-explorer/2593/workflows/df7dff4a-77fa-47a3-90ee-f3cfa0204892/jobs/14385
updating the version seems to fix that
https://app.circleci.com/pipelines/github/apollographql/embeddable-explorer/2594/workflows/399d8353-4514-4872-b181-8f96cf4ca0d8/jobs/14389
=> fix cdn upload - gcloud not found error

.changeset/clean-houses-clap.md, package-lock.json, packages/explorer/package.json
Added React v19 to peerDependencies to prevent npm error when installing this package in an app with React 19.
=> Add React 19 to peer dependencies
