apollographql/embeddable-explorer

- README.md
> update readme to be specific to embeddable explorer

- src/index.ts
in Studio-ui it is called `shouldPersistState`
https://github.com/mdg-private/studio-ui/blob/main/src/app/graph/routes.ts#L675
> 🐛 Typo: I named this query param wrong

- .changeset/config.json
- .changeset/cyan-owls-change.md
- .github/workflows/main.yml
- .github/workflows/release-pr.yaml
- package-lock.json
- package.json
This PR follows instructions in Trevor's template repo for new apollo repos. https://github.com/apollographql/typescript-repo-template#changeset-bot
This PR sets up changesets config for this repo. I _think_ the changeset will auto publish to npm since we have an npm key in the keys on this repo. I guess we will see when I merge this.
> Set up Changesets & auto publish github workflow

- renovate.json5
set up renovate bot using Trevor's template example
https://github.com/apollographql/typescript-repo-template#renovate
> Renovate bot config

- src/EmbeddedExplorer.ts
- src/constants.ts
- src/setupEmbedRelay.ts
> type outgoing post messages via a single function

- src/embeddedSandbox/EmbeddedSandbox.ts
Ii did this for the explorer, but not for sandbox, whoops!
> no border on embedded sandbox

- .changeset/many-chairs-sip.md
- index.ts
- package.json
- src/embeddedExplorer/examples/react-example/index.tsx
- src/embeddedExplorer/index.ts
- src/index.ts
- tsconfig.json
tsdx expects the index to be at src/index I believe
> move index to root

- src/embeddedExplorer/EmbeddedExplorer.ts
if a height style isn't set, set 100%! 
https://apollographql.quip.com/R5cOATFMz8s5/Explorer-Everywhere-QA#temp:C:PQY682c6c40391b48b196d435cc6
> Default to full height

- src/embeddedExplorer/EmbeddedExplorer.ts
- src/embeddedSandbox/EmbeddedSandbox.ts
- src/embeddedSandbox/examples/apollo-server.html
- src/embeddedSandbox/examples/as.html
we can come back to this when it doesn't break Apollo Server
> 🐛 don't change the css of the target element at all

- .changeset/green-falcons-accept.md
- src/embeddedExplorer/EmbeddedExplorer.ts
[JIRA](https://apollographql.atlassian.net/browse/NEBULA-1286)
> NEBULA-1286: Pretty print variables on new lines

- .circleci/config.yml
Not sure how this has been working 👀
> 🐛 circle ci config typo

- packages/explorer/README.md
forgot to commit the changes to this file for the new major version!
> fix explorer readme

- .circleci/config.yml
I realized that what I merged failed on main! Tested this on versioned upload
> fix commands to copy public folder to cdn buckets

- .github/pull_request_template.md
thinking this might be where people are most likely to need/want to see them :) 
would be even better if the bot could post the command in the message, but not sure how to configure that
> add PR template with changeset instructions for new contributors

- .changeset/purple-hornets-fail.md
- package-lock.json
- packages/explorer/package.json
- packages/explorer/src/helpers/postMessageRelayHelpers.ts
- packages/explorer/src/helpers/readMultipartWebStream.ts
- packages/sandbox/package.json
- packages/sandbox/src/helpers/postMessageRelayHelpers.ts
- packages/sandbox/src/helpers/readMultipartWebStream.ts
Update defer support (mostly copying changes from explorer) to
- fix content type parsing
- send accept header
- add incremental to the types
- send defer headers as well as initial headers
> Update defer support

- package-lock.json
- package.json
- packages/explorer/package.json
- packages/sandbox/package.json
we use volta in studio and its lovely :) lets use it here
no changeset necessary
> Add volta to package files

- .changeset/eleven-poems-melt.md
- packages/explorer/src/EmbeddedExplorer.ts
- packages/sandbox/src/EmbeddedSandbox.ts
we had a bit of repeated code here, as[ glasser pointed out in my copy-paste of this code in a closed PR](https://github.com/apollographql/apollo-server/pull/6715#discussion_r937029835), simplied it a wee bit
> lil logic cleanup

- .changeset/popular-phones-leave.md
- package-lock.json
- package.json
- packages/explorer/src/examples/react-example/package.json
- packages/sandbox/src/examples/react-example/package.json
I tested the umd & cjs-esm builds for both sandbox & explorer and everything builds & runs fine :) EASY!
this will let us update graphql-js :)
> TS 3.6 -> 4.8!

- .changeset/seven-grapes-walk.md
- .circleci/config.yml
- packages/explorer/src/index.cjs
- packages/explorer/src/react/index.cjs
- packages/sandbox/src/helpers/postMessageRelayHelpers.ts
- packages/sandbox/src/index.cjs
- packages/sandbox/src/react/index.cjs
[Previously](https://github.com/apollographql/embeddable-explorer/pull/183) I updated these files to have a cjs extension, but I didn't update the index.cjs files to point to them 😢
> 🐛 fix cjs build

- packages/explorer/src/EmbeddedExplorer.ts
- packages/sandbox/src/EmbeddedSandbox.ts
pass through initialState.collectionId & initialState.operationId for both Sandbox & Explorer
> NEBULA-2125: allow embedding by operation

- .changeset/breezy-apples-add.md
- packages/explorer/src/EmbeddedExplorer.ts
- packages/sandbox/src/EmbeddedSandbox.ts
https://apollograph.slack.com/archives/C025ENJA19Q/p1678296850595119?thread_ts=1678288648.578999&cid=C025ENJA19Q
> send referrer to studio via query param

- .circleci/config.yml
- package-lock.json
- package.json
> add bundlewatch

- .changeset/dull-bulldogs-rhyme.md
- .github/workflows/main.yml
- packages/explorer/src/examples/localDevelopmentExample-FileUpload.html
- packages/explorer/src/helpers/constructMultipartForm.ts
- packages/explorer/src/helpers/postMessageRelayHelpers.ts
- packages/explorer/src/setupEmbedRelay.ts
- packages/sandbox/src/examples/localDevelopmentExample.html
- packages/sandbox/src/helpers/constructMultipartForm.ts
- packages/sandbox/src/helpers/postMessageRelayHelpers.ts
- packages/sandbox/src/helpers/subscriptionPostMessageRelayHelpers.ts
- packages/sandbox/src/setupSandboxEmbedRelay.ts
[JIRA](https://apollographql.atlassian.net/browse/NEBULA-2181)
[Corresponding Studio-ui Embed PR
](https://github.com/mdg-private/studio-ui/pull/8269)
[Studio.apollographql.com PR
](https://github.com/mdg-private/studio-ui/pull/8269)
We now support file uploads in the embeds. We do this by converting uploaded files to byte arrays, sending via PM to the parent page, where the parent page converts those byte arrays back into files & performs [the same multipart form request ](https://github.com/mdg-private/studio-ui/pull/8269/files#diff-56e15e33990b5fbfa40f6c019d78ec5c444e383aea97b8bc254a07c00353a245)we make for uploads in studio.apollographql.com
1. add `__testLocal__` to `localDevelopmentExample.html` in the sandbox package in the `embeddable-explorer` repo & run the `Go Live` …
> NEBULA-2181: 📎 File upload in embeds

- .changeset/rotten-readers-add.md
- .circleci/config.yml
- .github/workflows/main.yml
- package-lock.json
- package.json
- packages/explorer-helpers/README.md
- packages/explorer-helpers/createRollupConfig.js
- packages/explorer-helpers/package.json
- packages/explorer-helpers/rollup.cjs-esm.config.js
- packages/explorer-helpers/src/constructMultipartForm.ts
- packages/explorer-helpers/src/index.cjs
- packages/explorer-helpers/src/index.ts
- packages/explorer-helpers/src/readMultipartWebStream.ts
- packages/explorer-helpers/src/types.ts
- packages/explorer-helpers/tsconfig.json
- packages/explorer/package.json
- packages/sandbox/package.json
precursor to embed-helpers package, with just readMultipartWebstream & createMultipartForm
> create explorer-helpers npm package

- .changeset/brave-moose-hang.md
- packages/explorer-helpers/src/index.ts
> export things I need

- .changeset/many-cherries-wait.md
- prepareForPublish.js
> also prepare new workspace explorer-helpers

- packages/explorer-helpers/LICENSE
- packages/explorer-helpers/package.json
- packages/explorer-helpers/prepareDist.js
> correctly copy over package.json file in the explorer-helpers package

- .changeset/popular-rules-sin.md
- package-lock.json
- package.json
- packages/explorer-helpers/src/readMultipartWebStream.ts
- packages/explorer/src/helpers/readMultipartWebStream.ts
- packages/sandbox/src/helpers/readMultipartWebStream.ts
I forgot to do this in the embeds :face-palm:
https://github.com/mdg-private/studio-ui/commit/d7277abf9df81a814b83c6e24eeac3819b8caa48
We definitely need to consolidate this code & only get it from one place. I was in the process of doing this before Proposals took over
> fix all the multipart streams

- .changeset/metal-rabbits-tell.md
- packages/explorer/src/EmbeddedExplorer.ts
> accept shouldShowGlobalHeader to pass through

- .changeset/big-eyes-compete.md
- packages/explorer/src/EmbeddedExplorer.ts
> make words consistent in display options

- .changeset/unlucky-dogs-yawn.md
- packages/explorer/src/EmbeddedExplorer.ts
> I was confused I guess

- .circleci/config.yml
- .github/workflows/main.yml
- package-lock.json
- package.json
> update node version to 18, 20, 22 in github actions

- .changeset/great-bats-fly.md
- packages/explorer/src/helpers/postMessageRelayHelpers.ts
- packages/explorer/src/helpers/subscriptionPostMessageRelayHelpers.ts
- packages/explorer/src/setupEmbedRelay.ts
- packages/sandbox/src/helpers/constants.ts
- packages/sandbox/src/helpers/postMessageRelayHelpers.ts
- packages/sandbox/src/helpers/subscriptionPostMessageRelayHelpers.ts
- packages/sandbox/src/setupSandboxEmbedRelay.ts
Check origin of messages against embedUrl before handling them.
> 🐛 fix: Check origin when handling messages
